import React from 'react';
import { Helmet } from 'react-helmet-async';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card.jsx';

const TermsOfServicePage = () => {
  return (
    <div className="min-h-[100dvh] bg-[#0a0a0f] text-white flex flex-col">
      <Helmet>
        <title>{`Terms of Service - FocusAfter35`}</title>
        <meta name="description" content="Terms of Service and usage conditions for FocusAfter35." />
        <link rel="canonical" href="https://focusafter35.com/terms-of-service" />
      </Helmet>

      <main className="flex-grow flex flex-col w-full">
        {/* Header Section */}
        <section className="w-full pt-24 pb-12 px-4 relative overflow-hidden">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,_var(--tw-gradient-stops))] from-[#c9a84c]/10 via-transparent to-transparent pointer-events-none" />
          <div className="max-w-3xl mx-auto text-center relative z-10">
            <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight mb-6 text-balance" style={{ letterSpacing: '-0.02em' }}>
              Terms of Service
            </h1>
            <p className="text-lg text-gray-400">
              Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
            </p>
          </div>
        </section>

        {/* Content Section */}
        <section className="w-full pb-24 px-4 max-w-4xl mx-auto space-y-8">
          <Card className="bg-white/5 border-white/10">
            <CardHeader>
              <CardTitle className="text-2xl text-[#c9a84c]">Website Usage Terms</CardTitle>
            </CardHeader>
            <CardContent className="text-gray-300 space-y-4 leading-relaxed">
              <p>
                By accessing or using FocusAfter35, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the service.
              </p>
              <p>
                Our services and tools are intended for personal, non-commercial use. You agree not to reproduce, duplicate, copy, sell, resell, or exploit any portion of the Service without express written permission by us.
              </p>
            </CardContent>
          </Card>

          <Card className="bg-white/5 border-white/10 border-l-4 border-l-destructive">
            <CardHeader>
              <CardTitle className="text-2xl text-destructive">Medical Disclaimer</CardTitle>
            </CardHeader>
            <CardContent className="text-gray-300 space-y-4 leading-relaxed">
              <p className="font-semibold text-white">
                The content on FocusAfter35 is not intended to be a substitute for professional medical advice, diagnosis, or treatment.
              </p>
              <p>
                Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition or hormonal symptoms. Never disregard professional medical advice or delay in seeking it because of something you have read on this website.
              </p>
            </CardContent>
          </Card>

          <Card className="bg-white/5 border-white/10">
            <CardHeader>
              <CardTitle className="text-2xl text-[#c9a84c]">Informational Purposes Only</CardTitle>
            </CardHeader>
            <CardContent className="text-gray-300 space-y-4 leading-relaxed">
              <p>
                All tools, calculators, quizzes, and trackers provided on FocusAfter35 are for educational and informational purposes only. The results generated by these tools do not constitute medical diagnoses.
              </p>
              <p>
                Hormonal transitions are complex and highly individual. Our content provides general guidance and potential symptom correlations based on aggregated scientific data, but your personal experience may vary.
              </p>
            </CardContent>
          </Card>

          <Card className="bg-white/5 border-white/10">
            <CardHeader>
              <CardTitle className="text-2xl text-[#c9a84c]">Limitation of Liability</CardTitle>
            </CardHeader>
            <CardContent className="text-gray-300 space-y-4 leading-relaxed">
              <p>
                In no event shall FocusAfter35, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
              </p>
            </CardContent>
          </Card>

          <Card className="bg-white/5 border-white/10">
            <CardHeader>
              <CardTitle className="text-2xl text-[#c9a84c]">Affiliate Disclosure</CardTitle>
            </CardHeader>
            <CardContent className="text-gray-300 space-y-4 leading-relaxed">
              <p>
                Some links on FocusAfter35 may be affiliate links. If you purchase a product or service through these links, we may receive a commission at no additional cost to you.
              </p>
              <p>
                We only recommend products and services that we believe provide value to our users navigating hormonal changes and cognitive wellness. However, it remains your responsibility to investigate whether any affiliate offers are right for you.
              </p>
            </CardContent>
          </Card>

          <Card className="bg-white/5 border-white/10">
            <CardHeader>
              <CardTitle className="text-2xl text-[#c9a84c]">Contact Information</CardTitle>
            </CardHeader>
            <CardContent className="text-gray-300 space-y-4 leading-relaxed">
              <p>
                If you have any questions about these Terms, please contact us:
              </p>
              <ul className="list-none space-y-2">
                <li>By email: <a href="mailto:legal@focusafter35.com" className="text-[#c9a84c] hover:underline">legal@focusafter35.com</a></li>
              </ul>
            </CardContent>
          </Card>
        </section>
      </main>
    </div>
  );
};

export default TermsOfServicePage;